agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index, TopicListView, TopicDetailView, TopicCreateView, TopicUpdateView, TopicDeleteView,
    NewspaperListView, NewspaperDetailView, NewspaperCreateView, NewspaperUpdateView, NewspaperDeleteView,
    RedactorListView, RedactorDetailView, RedactorCreateView,
    RedactorYearsUpdateView, RedactorFullUpdateView, RedactorDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/<int:pk>/",
        TopicDetailView.as_view(),
        name="topic-detail"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list",
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorYearsUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/full_update/",
        RedactorFullUpdateView.as_view(),
        name="redactor-full-update"
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),
]

app_name = "newspaper"

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg">
  <div class="navbar-brand" style="display: flex; gap: 0.5rem">
    {% load static %}
    <img src="{% static 'images/SiteIcon.png' %}" width="30" height="30">
    3rAgency
  </div>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newspaper:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newspaper:topic-list' %}">Topics</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newspaper:newspaper-list' %}">Newspapers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'newspaper:redactor-list' %}">Redactors</a>
      </li>
    </ul>
  </div>

  {% if user.is_authenticated %}
    <div class="float-right">
      {% if user.is_superuser %}
         <a href="/admin" class="btn btn-dark btn-sml">Admin page</a>
      {% endif %}
      <a href="{% url 'newspaper:redactor-detail' pk=user.id %}" class="btn btn-dark btn-sml">{{ user.username }}</a>
      <a href="{% url 'logout'%}?next={{request.path}}" class="btn btn-dark btn-sml">Logout</a>
    </div>
  {% else %}
    <div class="float-right">
      <a href="{% url 'login'%}?next={{request.path}}" class="btn btn-dark btn-sml">Login</a>
      <a href="{% url 'newspaper:redactor-create'%}?next={{request.path}}" class="btn btn-dark btn-sml">Register</a>
    </div>
  {% endif %}
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="btn btn-outline-dark">
          prev
        </a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="btn btn-outline-secondary">
        {{ page_obj.number }} of {{ paginator.num_pages }}
      </span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="btn btn-outline-dark">
          next
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}