agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls", namespace="newspaper")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index, TopicListView, TopicDetailView, TopicCreateView, TopicUpdateView, TopicDeleteView,
    NewspaperListView, NewspaperDetailView, NewspaperCreateView, NewspaperUpdateView, NewspaperDeleteView,
    RedactorListView, RedactorDetailView, RedactorCreateView,
    RedactorYearsUpdateView, RedactorFullUpdateView, RedactorDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/<int:pk>/",
        TopicDetailView.as_view(),
        name="topic-detail"
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create",
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update",
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete",
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list",
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create",
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update",
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete",
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list",
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorYearsUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/full_update/",
        RedactorFullUpdateView.as_view(),
        name="redactor-full-update"
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),
]

app_name = "newspaper"

newspaper/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Redactor(AbstractUser):
    years_of_experience = models.PositiveIntegerField(null=True)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"
        ordering = ["id"]

    def __str__(self):
        if self.first_name and self.last_name:
            return f"{self.username} ({self.first_name} {self.last_name})"
        return self.username


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(max_length=255)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="newspapers")
    published_date = models.DateField(null=True)
    publishers = models.ManyToManyField(Redactor, related_name="newspapers")

    class Meta:
        ordering = ["-published_date"]

    def __str__(self):
        return self.title

newspaper/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from newspaper.models import Newspaper, Redactor


class DateInput(forms.DateInput):
    input_type = "date"


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    published_date = forms.DateTimeField(
        widget=DateInput()
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class RedactorYearsUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["years_of_experience"]


class RedactorFullUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class SearchForm(forms.Form):
    search_by = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={
            "placeholder": "Search"
        })
    )

newspaper/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from django_superuser_required.views import SuperuserRequiredMixin
from newspaper.forms import (
    RedactorCreationForm,
    RedactorYearsUpdateForm,
    RedactorFullUpdateForm,
    NewspaperForm,
    SearchForm,
)
from newspaper.models import Redactor, Newspaper, Topic
from newspaper.permission_classes import StaffRequiredMixin


def index(request):
    """View function for the home page of the site."""

    num_redactors = Redactor.objects.count()
    num_newspapers = Newspaper.objects.count()
    num_topics = Topic.objects.count()

    num_visits = 1 + request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits

    context = {
        "num_redactors": num_redactors,
        "num_newspapers": num_newspapers,
        "num_topics": num_topics,
        "num_visits": num_visits,
    }

    return render(request, "newspaper/index.html", context=context)


class TopicListView(generic.ListView):
    model = Topic
    queryset = Topic.objects.all()
    context_object_name = "topic_list"
    template_name = "newspaper/topic_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context["search_form"] = SearchForm(
            initial={"search_by": self.request.GET.get("search_by", "")}
        )
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            result = self.queryset.filter(
                name__icontains=form.cleaned_data["search_by"]
            )
            return result
        return self.queryset


class TopicDetailView(generic.DetailView):
    model = Topic
    queryset = Topic.objects.prefetch_related("newspapers")


class TopicCreateView(StaffRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicUpdateView(StaffRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topic-list")


class TopicDeleteView(StaffRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topic-list")


class NewspaperListView(generic.ListView):
    model = Newspaper
    queryset = Newspaper.objects.select_related("topic")
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context["search_form"] = SearchForm(
            initial={"search_by": self.request.GET.get("search_by", "")}
        )
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            result = self.queryset.filter(
                title__icontains=form.cleaned_data["search_by"]
            )
            return result
        return self.queryset


class NewspaperDetailView(generic.DetailView):
    model = Newspaper
    queryset = Newspaper.objects.prefetch_related("publishers").select_related(
        "topic"
    )


class NewspaperCreateView(StaffRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperUpdateView(StaffRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDeleteView(StaffRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")


class RedactorListView(generic.ListView):
    model = get_user_model()
    queryset = get_user_model().objects.all()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context["search_form"] = SearchForm(
            initial={"search_by": self.request.GET.get("search_by", "")}
        )
        return context

    def get_queryset(self):
        form = SearchForm(self.request.GET)

        if form.is_valid():
            result = self.queryset.filter(
                username__icontains=form.cleaned_data["search_by"]
            )
            return result
        return self.queryset


class RedactorDetailView(generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers__topic")


class RedactorCreateView(generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorYearsUpdateView(StaffRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorYearsUpdateForm
    template_name = "newspaper/redactor_form.html"
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorFullUpdateView(SuperuserRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorFullUpdateForm
    template_name = "newspaper/redactor_form.html"
    success_url = reverse_lazy("newspaper:redactor-list")


class RedactorDeleteView(SuperuserRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactor-list")

templates/newspaper/index.html
{% extends "base.html" %}

{% block title %}
  | Home
{% endblock %}

{% block content %}
  <h1>3rAgency Home</h1>
  <hr>
  <p>Welcome to Best Newspaper Agency! On this site you can manage newspapers!</p>
  <h5>Our achievements</h5>

  <p>The 3rAgency has the following record counts:</p>
  <ul>
    <li><strong>Different topics:</strong> {{ num_topics }}</li>
    <li><strong>Newspaper issues:</strong> {{ num_newspapers }}</li>
    <li><strong>Redactors:</strong> {{ num_redactors }}</li>
  </ul>

  <p>You have visited this page
      {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}

templates/newspaper/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic {{ newspaper.title }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-dark">
    <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}" class="btn btn-secondary btn">Cancel</a>
  </form>
{% endblock %}

templates/newspaper/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ newspaper.title }}
    {% if user.is_staff %}
      <div class="float-right d-flex align-items-center">
        <a href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}" class="btn btn-dark">Update</a>
        <a href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}" class="btn btn-secondary">Delete</a>
      </div>
    {% endif %}
  </h1>
  <hr>

  <p>
    <strong>Topic: </strong>
    <a href="{% url 'newspaper:topic-detail' pk=newspaper.topic.id %}" style="color: black">
      {{ newspaper.topic.name }}
    </a>
  </p>

  <div class="container-fluid newspaper-content">
    <h4 style="text-align: center">{{ newspaper.title }}</h4>
    <p>{{ newspaper.content }}</p>
  </div>

  {% if newspaper.publishers.exists %}
    <div class="ml-3">
      <h5>Publishers:</h5>
      <table class="table table-bordered table-striped">
        <thead class="thead-dark">
          <th>ID</th>
          <th>Username</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Years of experience</th>
        </thead>

        {% for redactor in newspaper.publishers.all %}
          <tr>
            <td class="col-sm-1">
              <a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}" class="btn btn-dark btn-sm">
                {{ redactor.id }}
              </a>
            </td>
            <td style="vertical-align: middle">
              {{ redactor.username }}
            </td>
            <td style="vertical-align: middle">
              {{ redactor.first_name }}
            </td>
            <td style="vertical-align: middle">
              {{ redactor.last_name }}
            </td>
            <td style="vertical-align: middle">
              {% if redactor.years_of_experience %}
                {{ redactor.years_of_experience }}
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </table>
    {% endif %}
  </div>
{% endblock %}

templates/newspaper/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
  <hr>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-dark">
    <a href="{% url 'newspaper:newspaper-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/newspaper/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  | Newspapers
{% endblock %}

{% block content %}
  <h1>
    Newspapers
    {% if user.is_staff %}
      <div class="float-right d-flex align-items-center">
        <a href="{% url 'newspaper:newspaper-create' %}" class="btn btn-dark">Add</a>
      </div>
    {% endif %}
  </h1>
  <hr>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    &nbsp
    <input type="submit" value="🔍" class="btn btn-secondary btn-sm">
  </form>

  {% if newspaper_list %}
    List of our newspapers:
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
        <th>ID</th>
        <th>Title</th>
        <th>Topic</th>
        <th>Published Date</th>
      </thead>

      {% for newspaper in newspaper_list %}
        <tr>
          <td class="col-sm-1">
            <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}" class="btn btn-dark btn-sm">
              {{ newspaper.id }}
            </a>
          </td>
          <td style="vertical-align: middle">
            {{ newspaper.title }}
          </td>
          <td style="vertical-align: middle">
            {{ newspaper.topic }}
          </td>
          <td style="vertical-align: middle">
            {{ newspaper.published_date }}
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>Newspapers not found.</p>
  {% endif %}
{% endblock %}

templates/newspaper/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete redactor {{ redactor.username }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-dark">
    <a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}" class="btn btn-secondary btn">Cancel</a>
  </form>
{% endblock %}

templates/newspaper/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    User: {{ redactor.username }}

    {% if not redactor.is_staff %}
      <span style="color: gray">(not confirmed)</span>
    {% endif %}

    {% if user.is_superuser %}
      <div class="float-right d-flex align-items-center">
        <a href="{% url 'newspaper:redactor-full-update' pk=redactor.id %}" class="btn btn-dark">Update</a>
        <a href="{% url 'newspaper:redactor-delete' pk=redactor.id %}" class="btn btn-secondary">Delete</a>
      </div>
    {% endif %}
  </h1>
  <hr>

  <p>
    <strong>First name:</strong>
    {% if redactor.first_name %}
      {{ redactor.first_name }}
    {% else %}
      <span style="color: gray">None</span>
    {% endif %}
  </p>

  <p>
    <strong>Last name:</strong>
    {% if redactor.last_name %}
      {{ redactor.last_name }}
    {% else %}
      <span style="color: gray">None</span>
    {% endif %}
  </p>

  <p>
    <strong>Username:</strong>
    {{ redactor.username }}
  </p>

  <p>
    <strong>Email:</strong>
    {% if redactor.email %}
      {{ redactor.email }}
    {% else %}
      <span style="color: gray">None</span>
    {% endif %}
  </p>

  <p>
    <strong>Years of experience:</strong> {{ redactor.years_of_experience }}

    {% if user.is_staff %}
      <a href="{% url 'newspaper:redactor-update' pk=redactor.id %}?next={{request.path}}"
         class="btn btn-secondary btn-sm">
        Update
      </a>
    {% endif %}
  </p>

  {% if redactor.newspapers.exists %}
    <div class="ml-3">
      <h4>List of newspapers:</h4>
      <table class="table table-bordered table-striped">
        <thead class="thead-dark">
          <th>ID</th>
          <th>Title</th>
          <th>Topic</th>
          <th>Published Date</th>
        </thead>

        {% for newspaper in redactor.newspapers.all %}
          <tr>
            <td class="col-sm-1">
              <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}" class="btn btn-dark btn-sm">
                {{ newspaper.id }}
              </a>
            </td>
            <td style="vertical-align: middle">
              {{ newspaper.title }}
            </td>
            <td style="vertical-align: middle">
              {{ newspaper.topic }}
            </td>
            <td style="vertical-align: middle">
              {{ newspaper.published_date }}
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  {% endif %}
{% endblock %}

templates/newspaper/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} redactor {{ redactor.username }}</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="{{ object|yesno:"Update,Register" }}" class="btn btn-dark">
    <input type="hidden" name="next" value="{{ next }}" />
    <a href="{% url 'newspaper:redactor-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/newspaper/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  | Redactors
{% endblock %}

{% block content %}
  <h1>
    Redactors
    {% if user.is_superuser %}
      <div class="float-right d-flex align-items-center">
        <a href="{% url 'newspaper:redactor-create' %}" class="btn btn-dark">Add</a>
      </div>
    {% endif %}
  </h1>
  <hr>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    &nbsp
    <input type="submit" value="🔍" class="btn btn-secondary btn-sm">
  </form>

  {% if redactor_list %}
    List of our redactors:
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </thead>

      {% for redactor in redactor_list %}
        <tr>
          <td class="col-sm-1">
            <a href="{% url 'newspaper:redactor-detail' pk=redactor.id %}" class="btn btn-dark btn-sm">
              {{ redactor.id }}
            </a>
          </td>
          <td style="vertical-align: middle">
              {{ redactor.username }}
              {% if not redactor.is_staff %}
                <span style="color: gray">(not confirmed)</span>
              {% endif %}
          </td>
          <td style="vertical-align: middle">
              {{ redactor.first_name }}
          </td>
          <td style="vertical-align: middle">
              {{ redactor.last_name }}
          </td>
          <td style="vertical-align: middle">
            {% if redactor.years_of_experience %}
              {{ redactor.years_of_experience }}
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>Redactors not found.</p>
  {% endif %}
{% endblock %}

templates/newspaper/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic {{ topic.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-dark">
    <a href="{% url 'newspaper:topic-detail' pk=topic.id %}" class="btn btn-secondary btn">Cancel</a>
  </form>
{% endblock %}

templates/newspaper/topic_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Topic: {{ topic.name }}
    {% if user.is_staff %}
      <div class="float-right d-flex align-items-center">
        <a href="{% url 'newspaper:topic-update' pk=topic.id %}" class="btn btn-dark">Update</a>
        <a href="{% url 'newspaper:topic-delete' pk=topic.id %}" class="btn btn-secondary">Delete</a>
      </div>
    {% endif %}
  </h1>
  <hr>

  {% if topic.newspapers.exists %}
    <div class="ml-3">
      <h4>List of newspapers:</h4>
      <table class="table table-bordered table-striped">
        <thead class="thead-dark">
          <th>ID</th>
          <th>Title</th>
          <th>Topic</th>
          <th>Published Date</th>
        </thead>

        {% for newspaper in topic.newspapers.all %}
          <tr>
            <td>
              <a href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}" class="btn btn-dark btn-sm">
                {{ newspaper.id }}
              </a>
            </td>
            <td style="vertical-align: middle">
              {{ newspaper.title }}
            </td>
            <td style="vertical-align: middle">
              {{ newspaper.topic }}
            </td>
            <td style="vertical-align: middle">
              {{ newspaper.published_date }}
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  {% else %}
    No newspapers.
  {% endif %}
{% endblock %}

templates/newspaper/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} topic</h1>
  <hr>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-dark">
    <a href="{% url 'newspaper:topic-list' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/newspaper/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}
  | Topics
{% endblock %}

{% block content %}
  <h1>
    Topics
    {% if user.is_staff %}
      <div class="float-right d-flex align-items-center">
        <a href="{% url 'newspaper:topic-create' %}" class="btn btn-dark">Add</a>
      </div>
    {% endif %}
  </h1>
  <hr>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    &nbsp
    <input type="submit" value="🔍" class="btn btn-secondary btn-sm">
  </form>

  {% if topic_list %}
    List of our newspapers topics:
    <table class="table table-bordered table-striped">
      <thead class="thead-dark">
        <th>ID</th>
        <th>Name</th>
      </thead>

      {% for topic in topic_list %}
        <tr>
          <td class="col-sm-1">
            <a href="{% url 'newspaper:topic-detail' pk=topic.id %}" class="btn btn-dark btn-sm">
              {{ topic.id }}
            </a>
          </td>
          <td style="vertical-align: middle">
            {{ topic.name }}
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>Topics not found.</p>
  {% endif %}
{% endblock %}